//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiingJumps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ski_jumps
    {
        public int JumpID { get; set; }
        public int JumperID { get; set; }
        public int JumpinhHillID { get; set; }
        public decimal Meters { get; set; }
        public decimal Points { get; set; }
    }
}
