//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiingJumps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ski_jumping_hills
    {
        public int JumpingHillID { get; set; }
        public string Name { get; set; }
        public int Height { get; set; }
        public int CityID { get; set; }
        public int CountryID { get; set; }
    }
}
